# Generated by Django 4.2.3 on 2023-07-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0002_delete_cliente_delete_ventas"),
        ("clientes", "0002_remove_ventas_cliente_remove_ventas_producto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ventas",
            fields=[
                ("ventas_id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.producto",
                    ),
                ),
            ],
        ),
    ]
