# Generated by Django 4.2.3 on 2023-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_delete_cliente_delete_ventas"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ventas",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="ventas",
            name="producto",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.DeleteModel(
            name="Ventas",
        ),
    ]
