# Generated by Django 4.2.3 on 2023-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_remove_ventas_cliente_remove_ventas_producto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="regimen_afip",
            field=models.CharField(
                choices=[
                    ("RI", "Responsable Inscripto"),
                    ("EX", "Exento/Monotributista"),
                    ("CF", "Consumidor Final"),
                ],
                default="CF",
                max_length=2,
            ),
        ),
    ]
