# Generated by Django 4.2.3 on 2023-07-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "cliente_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                ("mov", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("descripcion", models.TextField()),
                ("mov", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                ("ventas_id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_app.producto",
                    ),
                ),
            ],
        ),
    ]
